version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - gocritic
    - godot
    - govet
    - ineffassign
    - misspell
    - noctx
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  govet:
    enable-all: true
  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
