// Package semconv provides OpenInference semantic conventions for tracing.
//
// These conventions define the attribute keys and well-known values used to
// annotate spans produced by LLM applications, agents, and related systems
// following the OpenInference specification:
// https://arize-ai.github.io/openinference/spec/semantic_conventions.html
package semconv

// Input span attribute keys.
const (
	// InputValue is the input value for any span.
	InputValue = "input.value"

	// InputMimeType is the MIME type of the input value.
	InputMimeType = "input.mime_type"
)

// Output span attribute keys.
const (
	// OutputValue is the output value for any span.
	OutputValue = "output.value"

	// OutputMimeType is the MIME type of the output value.
	OutputMimeType = "output.mime_type"
)

// LLM span attribute keys.
const (
	// LLMInputMessages is the list of messages sent to the LLM (chat completions API).
	LLMInputMessages = "llm.input_messages"

	// LLMOutputMessages is the list of messages received from the LLM.
	LLMOutputMessages = "llm.output_messages"

	// LLMModelName is the name of the language model.
	LLMModelName = "llm.model_name"

	// LLMPrompts is the list of prompts sent to the completions API (legacy).
	LLMPrompts = "llm.prompts"

	// LLMChoices is the list of text choices returned from the completions API (legacy).
	LLMChoices = "llm.choices"

	// LLMInvocationParameters is the JSON representation of parameters passed to the LLM.
	LLMInvocationParameters = "llm.invocation_parameters"

	// LLMProviderKey is the attribute key for the hosting provider of the LLM (e.g. "azure").
	// Use [LLMProvider] values for well-known providers.
	LLMProviderKey = "llm.provider"

	// LLMSystemKey is the attribute key for the AI product as identified by the client or server.
	// Use [LLMSystem] values for well-known systems.
	LLMSystemKey = "llm.system"

	// LLMFunctionCall is the JSON representation of a function call made by the LLM.
	LLMFunctionCall = "llm.function_call"

	// LLMTools is the list of tools advertised to the LLM.
	LLMTools = "llm.tools"
)

// LLM token count attribute keys.
const (
	// LLMTokenCountPrompt is the number of tokens in the prompt.
	LLMTokenCountPrompt = "llm.token_count.prompt"

	// LLMTokenCountCompletion is the number of tokens in the completion.
	LLMTokenCountCompletion = "llm.token_count.completion"

	// LLMTokenCountTotal is the total number of tokens used.
	LLMTokenCountTotal = "llm.token_count.total"

	// LLMTokenCountPromptDetails is the key prefix for prompt token count details.
	LLMTokenCountPromptDetails = "llm.token_count.prompt_details"

	// LLMTokenCountPromptDetailsCacheWrite is the number of prompt tokens written to cache.
	LLMTokenCountPromptDetailsCacheWrite = "llm.token_count.prompt_details.cache_write"

	// LLMTokenCountPromptDetailsCacheRead is the number of prompt tokens read from cache.
	LLMTokenCountPromptDetailsCacheRead = "llm.token_count.prompt_details.cache_read"

	// LLMTokenCountPromptDetailsCacheInput is the number of cached input tokens in the prompt.
	LLMTokenCountPromptDetailsCacheInput = "llm.token_count.prompt_details.cache_input"

	// LLMTokenCountPromptDetailsAudio is the number of audio input tokens in the prompt.
	LLMTokenCountPromptDetailsAudio = "llm.token_count.prompt_details.audio"

	// LLMTokenCountCompletionDetails is the key prefix for completion token count details.
	LLMTokenCountCompletionDetails = "llm.token_count.completion_details"

	// LLMTokenCountCompletionDetailsReasoning is the number of reasoning tokens in the completion.
	LLMTokenCountCompletionDetailsReasoning = "llm.token_count.completion_details.reasoning"

	// LLMTokenCountCompletionDetailsAudio is the number of audio tokens generated by the model.
	LLMTokenCountCompletionDetailsAudio = "llm.token_count.completion_details.audio"
)

// LLM cost attribute keys. All monetary values are in USD.
const (
	// LLMCost is the key prefix for LLM cost information.
	LLMCost = "llm.cost"

	// LLMCostPrompt is the cost of the prompt tokens in USD.
	LLMCostPrompt = "llm.cost.prompt"

	// LLMCostCompletion is the cost of the completion tokens in USD.
	LLMCostCompletion = "llm.cost.completion"

	// LLMCostTotal is the total cost of the LLM call in USD.
	LLMCostTotal = "llm.cost.total"

	// LLMCostInput is the cost of input tokens in USD.
	LLMCostInput = "llm.cost.prompt_details.input"

	// LLMCostOutput is the cost of output tokens in USD.
	LLMCostOutput = "llm.cost.completion_details.output"

	// LLMCostCompletionDetailsReasoning is the cost of reasoning tokens in the completion in USD.
	LLMCostCompletionDetailsReasoning = "llm.cost.completion_details.reasoning"

	// LLMCostCompletionDetailsAudio is the cost of audio tokens in the completion in USD.
	LLMCostCompletionDetailsAudio = "llm.cost.completion_details.audio"

	// LLMCostPromptDetailsCacheWrite is the cost of prompt tokens written to cache in USD.
	LLMCostPromptDetailsCacheWrite = "llm.cost.prompt_details.cache_write"

	// LLMCostPromptDetailsCacheRead is the cost of prompt tokens read from cache in USD.
	LLMCostPromptDetailsCacheRead = "llm.cost.prompt_details.cache_read"

	// LLMCostPromptDetailsCacheInput is the cost of cached input tokens in the prompt in USD.
	LLMCostPromptDetailsCacheInput = "llm.cost.prompt_details.cache_input"

	// LLMCostPromptDetailsAudio is the cost of audio tokens in the prompt in USD.
	LLMCostPromptDetailsAudio = "llm.cost.prompt_details.audio"
)

// LLM prompt template attribute keys.
const (
	// PromptTemplateVariables is the JSON representation of variables used in the prompt template.
	PromptTemplateVariables = "llm.prompt_template.variables"

	// PromptTemplateTemplate is the prompt template string.
	PromptTemplateTemplate = "llm.prompt_template.template"

	// PromptTemplateVersion is the version of the prompt template.
	PromptTemplateVersion = "llm.prompt_template.version"
)

// Message attribute keys (for individual messages within LLM input/output lists).
const (
	// MessageRole is the role of the entity in a message (e.g. "user", "system", "assistant").
	MessageRole = "message.role"

	// MessageContent is the text content of a message.
	MessageContent = "message.content"

	// MessageContents is the array of content objects for a message (multimodal).
	MessageContents = "message.contents"

	// MessageName is the name of the function or tool that produced a tool/function role message.
	MessageName = "message.name"

	// MessageFunctionCallName is the name of the function called by the LLM.
	MessageFunctionCallName = "message.function_call_name"

	// MessageFunctionCallArgumentsJSON is the function call arguments as a JSON string.
	MessageFunctionCallArgumentsJSON = "message.function_call_arguments_json"

	// MessageToolCalls is the list of tool calls generated by the model.
	MessageToolCalls = "message.tool_calls"

	// MessageToolCallID is the tool call result identifier corresponding to [ToolCallID].
	MessageToolCallID = "message.tool_call_id"
)

// MessageContent attribute keys (for individual content items within a message).
const (
	// MessageContentType is the type of a content item (e.g. "text", "image").
	MessageContentType = "message_content.type"

	// MessageContentText is the text content of a content item.
	MessageContentText = "message_content.text"

	// MessageContentImage is the image content of a content item.
	MessageContentImage = "message_content.image"
)

// ToolCall attribute keys.
const (
	// ToolCallFunctionName is the name of the function invoked by a tool call.
	ToolCallFunctionName = "tool_call.function.name"

	// ToolCallFunctionArgumentsJSON is the function arguments as a JSON string.
	ToolCallFunctionArgumentsJSON = "tool_call.function.arguments"

	// ToolCallID is the unique identifier for a tool call.
	ToolCallID = "tool_call.id"
)

// Image attribute keys.
const (
	// ImageURL is the HTTP or base64 URL of an image.
	ImageURL = "image.url"
)

// Audio attribute keys.
const (
	// AudioURL is the URL of an audio file.
	AudioURL = "audio.url"

	// AudioMimeType is the MIME type of the audio file.
	AudioMimeType = "audio.mime_type"

	// AudioTranscript is the transcript of the audio file.
	AudioTranscript = "audio.transcript"
)

// Document attribute keys.
const (
	// DocumentID is the unique identifier of a document.
	DocumentID = "document.id"

	// DocumentContent is the content of a document.
	DocumentContent = "document.content"

	// DocumentScore is the relevance score of a document.
	DocumentScore = "document.score"

	// DocumentMetadata is the metadata of a document as a JSON string.
	DocumentMetadata = "document.metadata"
)

// Embedding attribute keys.
const (
	// EmbeddingEmbeddings is the list root for embedding objects.
	EmbeddingEmbeddings = "embedding.embeddings"

	// EmbeddingText is the text that was embedded to create the vector.
	EmbeddingText = "embedding.text"

	// EmbeddingModelName is the name of the embedding model.
	EmbeddingModelName = "embedding.model_name"

	// EmbeddingVector is the embedding vector (list of floats).
	EmbeddingVector = "embedding.vector"

	// EmbeddingInvocationParameters is the JSON string of parameters sent to the embedding model.
	EmbeddingInvocationParameters = "embedding.invocation_parameters"
)

// Retrieval attribute keys.
const (
	// RetrievalDocuments is the list of retrieved documents.
	RetrievalDocuments = "retrieval.documents"
)

// Reranker attribute keys.
const (
	// RerankerInputDocuments is the list of documents used as input to the reranker.
	RerankerInputDocuments = "reranker.input_documents"

	// RerankerOutputDocuments is the list of documents output by the reranker.
	RerankerOutputDocuments = "reranker.output_documents"

	// RerankerQuery is the query string used for reranking.
	RerankerQuery = "reranker.query"

	// RerankerModelName is the name of the reranker model.
	RerankerModelName = "reranker.model_name"

	// RerankerTopK is the top-k parameter for the reranker.
	RerankerTopK = "reranker.top_k"
)

// Tool attribute keys.
const (
	// ToolName is the name of a tool.
	ToolName = "tool.name"

	// ToolDescription is the description of a tool.
	ToolDescription = "tool.description"

	// ToolParameters is the parameters definition for invoking the tool as a JSON string.
	ToolParameters = "tool.parameters"

	// ToolJSONSchema is the JSON schema of the tool input.
	ToolJSONSchema = "tool.json_schema"

	// ToolID is the identifier for the result of the tool call (corresponding to [ToolCallID]).
	ToolID = "tool.id"
)

// Session and user attribute keys.
const (
	// SessionID is the unique session identifier used to correlate spans in a session.
	SessionID = "session.id"

	// UserID is the unique user identifier used to correlate spans for a user.
	UserID = "user.id"
)

// Prompt attribute keys.
const (
	// PromptVendor is the vendor or origin of the prompt (e.g. "langsmith", "portkey").
	PromptVendor = "prompt.vendor"

	// PromptID is a vendor-specific identifier for the prompt.
	PromptID = "prompt.id"

	// PromptURL is a vendor-specific URL used to locate the prompt.
	PromptURL = "prompt.url"
)

// Agent attribute keys.
const (
	// AgentName is the name of the agent.
	AgentName = "agent.name"
)

// Graph attribute keys.
const (
	// GraphNodeID is the id of the node in the execution graph.
	GraphNodeID = "graph.node.id"

	// GraphNodeName is the human-readable name of the node in the execution graph.
	GraphNodeName = "graph.node.name"

	// GraphNodeParentID is the id of the parent node; empty implies root.
	GraphNodeParentID = "graph.node.parent_id"
)

// Generic attribute keys.
const (
	// Metadata stores user-defined key-value pairs for a span as a JSON string.
	Metadata = "metadata"

	// TagTags is the list of tags associated with a span.
	TagTags = "tag.tags"
)

// OpenInference attribute keys.
const (
	// OpenInferenceSpanKindKey is the attribute key for the OpenInference span kind.
	// Use [OpenInferenceSpanKind] values for well-known kinds.
	OpenInferenceSpanKindKey = "openinference.span.kind"

	// ProjectName is the project name used to group traces for OpenInference-compatible services.
	ProjectName = "openinference.project.name"
)

// Exception attribute keys (reserved by the OpenInference spec).
const (
	// ExceptionEscaped indicates whether the exception escaped the span's scope.
	ExceptionEscaped = "exception.escaped"

	// ExceptionMessage is the detailed message describing the exception.
	ExceptionMessage = "exception.message"

	// ExceptionStacktrace is the stack trace of the exception.
	ExceptionStacktrace = "exception.stacktrace"

	// ExceptionType is the type of exception that was thrown.
	ExceptionType = "exception.type"
)
