// Package semconv provides OpenInference semantic conventions for tracing.
//
// These conventions define the attribute keys used to annotate spans produced
// by LLM applications, agents, and related systems that follow the OpenInference
// specification. See https://arize-ai.github.io/openinference/spec/semantic_conventions.html
// for the full specification.
package semconv

// Input span attributes.
const (
	// InputValue is the input value for any span.
	InputValue = "input.value"

	// InputMimeType is the MIME type of the input value.
	InputMimeType = "input.mime_type"
)

// Output span attributes.
const (
	// OutputValue is the output value for any span.
	OutputValue = "output.value"

	// OutputMimeType is the MIME type of the output value.
	OutputMimeType = "output.mime_type"
)

// LLM span attributes.
const (
	// LLMInputMessages is the list of messages sent to the LLM (e.g. OpenAI chat completions).
	LLMInputMessages = "llm.input_messages"

	// LLMOutputMessages is the list of messages received from the LLM.
	LLMOutputMessages = "llm.output_messages"

	// LLMModelName is the name of the LLM model.
	LLMModelName = "llm.model_name"

	// LLMPrompts is the list of prompts sent to the LLM (legacy completions API).
	LLMPrompts = "llm.prompts"

	// LLMInvocationParameters is the JSON representation of parameters passed to the LLM.
	LLMInvocationParameters = "llm.invocation_parameters"

	// LLMProvider is the provider of the inferences (e.g. the cloud provider).
	LLMProvider = "llm.provider"

	// LLMSystem is the AI product as identified by the client or server.
	LLMSystem = "llm.system"

	// LLMFunctionCall is the JSON representation of a function call made by the LLM.
	LLMFunctionCall = "llm.function_call"

	// LLMTools is the list of tools advertised to the LLM.
	LLMTools = "llm.tools"
)

// LLM token count attributes.
const (
	// LLMTokenCountPrompt is the number of tokens in the prompt.
	LLMTokenCountPrompt = "llm.token_count.prompt"

	// LLMTokenCountCompletion is the number of tokens in the completion.
	LLMTokenCountCompletion = "llm.token_count.completion"

	// LLMTokenCountTotal is the total number of tokens used in the transaction.
	LLMTokenCountTotal = "llm.token_count.total"

	// LLMTokenCountPromptDetails is the key prefix for additional prompt token count details.
	LLMTokenCountPromptDetails = "llm.token_count.prompt_details"

	// LLMTokenCountPromptDetailsCacheWrite is the number of prompt tokens written to cache.
	LLMTokenCountPromptDetailsCacheWrite = "llm.token_count.prompt_details.cache_write"

	// LLMTokenCountPromptDetailsCacheRead is the number of prompt tokens read from cache.
	LLMTokenCountPromptDetailsCacheRead = "llm.token_count.prompt_details.cache_read"

	// LLMTokenCountPromptDetailsCacheInput is the number of input tokens in the prompt that were cached.
	LLMTokenCountPromptDetailsCacheInput = "llm.token_count.prompt_details.cache_input"

	// LLMTokenCountPromptDetailsAudio is the number of audio tokens in the prompt.
	LLMTokenCountPromptDetailsAudio = "llm.token_count.prompt_details.audio"

	// LLMTokenCountCompletionDetails is the key prefix for additional completion token count details.
	LLMTokenCountCompletionDetails = "llm.token_count.completion_details"

	// LLMTokenCountCompletionDetailsReasoning is the number of tokens used for reasoning steps.
	LLMTokenCountCompletionDetailsReasoning = "llm.token_count.completion_details.reasoning"

	// LLMTokenCountCompletionDetailsAudio is the number of audio tokens generated by the model.
	LLMTokenCountCompletionDetailsAudio = "llm.token_count.completion_details.audio"
)

// LLM cost attributes. All monetary values are in USD.
const (
	// LLMCost is the key prefix for cost information.
	LLMCost = "llm.cost"

	// LLMCostPrompt is the cost of the prompt tokens in USD.
	LLMCostPrompt = "llm.cost.prompt"

	// LLMCostCompletion is the cost of the completion tokens in USD.
	LLMCostCompletion = "llm.cost.completion"

	// LLMCostTotal is the total cost of the LLM call in USD (prompt + completion).
	LLMCostTotal = "llm.cost.total"

	// LLMCostInput is the cost of input tokens in USD.
	LLMCostInput = "llm.cost.prompt_details.input"

	// LLMCostOutput is the cost of output tokens in USD.
	LLMCostOutput = "llm.cost.completion_details.output"

	// LLMCostCompletionDetailsReasoning is the cost of reasoning steps in the completion in USD.
	LLMCostCompletionDetailsReasoning = "llm.cost.completion_details.reasoning"

	// LLMCostCompletionDetailsAudio is the cost of audio tokens in the completion in USD.
	LLMCostCompletionDetailsAudio = "llm.cost.completion_details.audio"

	// LLMCostPromptDetailsCacheWrite is the cost of prompt tokens written to cache in USD.
	LLMCostPromptDetailsCacheWrite = "llm.cost.prompt_details.cache_write"

	// LLMCostPromptDetailsCacheRead is the cost of prompt tokens read from cache in USD.
	LLMCostPromptDetailsCacheRead = "llm.cost.prompt_details.cache_read"

	// LLMCostPromptDetailsCacheInput is the cost of input tokens in the prompt that were cached in USD.
	LLMCostPromptDetailsCacheInput = "llm.cost.prompt_details.cache_input"

	// LLMCostPromptDetailsAudio is the cost of audio tokens in the prompt in USD.
	LLMCostPromptDetailsAudio = "llm.cost.prompt_details.audio"
)

// LLM prompt template attributes.
const (
	// PromptTemplateVariables is the JSON representation of variables used in the prompt template.
	PromptTemplateVariables = "llm.prompt_template.variables"

	// PromptTemplateTemplate is the prompt template string.
	PromptTemplateTemplate = "llm.prompt_template.template"

	// PromptTemplateVersion is the version of the prompt template.
	PromptTemplateVersion = "llm.prompt_template.version"
)

// Message span attributes (for individual messages within LLM input/output).
const (
	// MessageRole is the role that the LLM assumes the message is from.
	MessageRole = "message.role"

	// MessageContent is the content of the message.
	MessageContent = "message.content"

	// MessageContents is the array of content objects for the message.
	MessageContents = "message.contents"

	// MessageName is the name associated with the message (used for role 'function').
	MessageName = "message.name"

	// MessageFunctionCallName is the name of the function called by the LLM.
	MessageFunctionCallName = "message.function_call_name"

	// MessageFunctionCallArgumentsJSON is the arguments of the function call as a JSON string.
	MessageFunctionCallArgumentsJSON = "message.function_call_arguments_json"

	// MessageToolCalls is the list of tool calls generated by the model.
	MessageToolCalls = "message.tool_calls"

	// MessageToolCallID is the id of the tool call on a "tool" role message.
	MessageToolCallID = "message.tool_call_id"
)

// MessageContent span attributes (for individual content items within a message).
const (
	// MessageContentType is the type of content (e.g. "text", "image").
	MessageContentType = "message_content.type"

	// MessageContentText is the text content of a message.
	MessageContentText = "message_content.text"

	// MessageContentImage is the image content of a message.
	MessageContentImage = "message_content.image"
)

// ToolCall span attributes.
const (
	// ToolCallFunctionName is the name of the function called via a tool call.
	ToolCallFunctionName = "tool_call.function.name"

	// ToolCallFunctionArgumentsJSON is the arguments of the tool call function as a JSON string.
	ToolCallFunctionArgumentsJSON = "tool_call.function.arguments"

	// ToolCallID is the identifier of the tool call.
	ToolCallID = "tool_call.id"
)

// Image span attributes.
const (
	// ImageURL is the HTTP or base64 URL of an image.
	ImageURL = "image.url"
)

// Audio span attributes.
const (
	// AudioURL is the URL of an audio file.
	AudioURL = "audio.url"

	// AudioMimeType is the MIME type of the audio content.
	AudioMimeType = "audio.mime_type"

	// AudioTranscript is the audio transcript as text.
	AudioTranscript = "audio.transcript"
)

// Document span attributes.
const (
	// DocumentID is the identifier of a document.
	DocumentID = "document.id"

	// DocumentContent is the content of a document.
	DocumentContent = "document.content"

	// DocumentScore is the relevance score of a document.
	DocumentScore = "document.score"

	// DocumentMetadata is the metadata of a document as a JSON string.
	DocumentMetadata = "document.metadata"
)

// Embedding span attributes.
const (
	// EmbeddingEmbeddings is the list root for embeddings.
	EmbeddingEmbeddings = "embedding.embeddings"

	// EmbeddingText is the text that was embedded to create the vector.
	EmbeddingText = "embedding.text"

	// EmbeddingModelName is the name of the model used to create the embedding vector.
	EmbeddingModelName = "embedding.model_name"

	// EmbeddingVector is the embedding vector.
	EmbeddingVector = "embedding.vector"
)

// Retrieval span attributes.
const (
	// RetrievalDocuments is the list of retrieved documents.
	RetrievalDocuments = "retrieval.documents"
)

// Reranker span attributes.
const (
	// RerankerInputDocuments is the list of documents used as input to the reranker.
	RerankerInputDocuments = "reranker.input_documents"

	// RerankerOutputDocuments is the list of documents output by the reranker.
	RerankerOutputDocuments = "reranker.output_documents"

	// RerankerQuery is the query string used for reranking.
	RerankerQuery = "reranker.query"

	// RerankerModelName is the name of the reranker model.
	RerankerModelName = "reranker.model_name"

	// RerankerTopK is the top-k parameter for the reranker.
	RerankerTopK = "reranker.top_k"
)

// Tool span attributes.
const (
	// ToolName is the name of a tool.
	ToolName = "tool.name"

	// ToolDescription is the description of a tool.
	ToolDescription = "tool.description"

	// ToolParameters is the parameters of the tool as a JSON string.
	ToolParameters = "tool.parameters"

	// ToolJSONSchema is the JSON schema of a tool input (recommended to use OpenAI tool calling format).
	ToolJSONSchema = "tool.json_schema"

	// ToolID is the identifier for the result of the tool call.
	ToolID = "tool.id"
)

// Session and user span attributes.
const (
	// SessionID is the session identifier used to correlate spans in a single session.
	SessionID = "session.id"

	// UserID is the user identifier used to correlate spans for a single user.
	UserID = "user.id"
)

// Prompt span attributes.
const (
	// PromptVendor is the vendor or origin of the prompt.
	PromptVendor = "prompt.vendor"

	// PromptID is a vendor-specific identifier for the prompt.
	PromptID = "prompt.id"

	// PromptURL is a vendor-specific URL used to locate the prompt.
	PromptURL = "prompt.url"
)

// Agent span attributes.
const (
	// AgentName is the name of the agent.
	AgentName = "agent.name"
)

// Graph span attributes.
const (
	// GraphNodeID is the id of the node in the execution graph.
	GraphNodeID = "graph.node.id"

	// GraphNodeName is the human-readable name of the node in the execution graph.
	GraphNodeName = "graph.node.name"

	// GraphNodeParentID is the id of the parent node in the execution graph.
	GraphNodeParentID = "graph.node.parent_id"
)

// Generic span attributes.
const (
	// Metadata stores user-defined key-value pairs for a span.
	Metadata = "metadata"

	// TagTags is the list of tags associated with a span.
	TagTags = "tag.tags"
)

// OpenInference span kind attribute.
const (
	// OpenInferenceSpanKindKey is the attribute key for the OpenInference span kind.
	OpenInferenceSpanKindKey = "openinference.span.kind"
)

// Resource attributes.
const (
	// ProjectName is the project name used to group traces for OpenInference compatible services.
	ProjectName = "openinference.project.name"
)

// OpenInferenceSpanKind represents the kind of an OpenInference span.
type OpenInferenceSpanKind string

const (
	// SpanKindLLM identifies a span that calls a large language model.
	SpanKindLLM OpenInferenceSpanKind = "LLM"

	// SpanKindChain identifies a span that chains multiple calls together.
	SpanKindChain OpenInferenceSpanKind = "CHAIN"

	// SpanKindTool identifies a span that calls a tool.
	SpanKindTool OpenInferenceSpanKind = "TOOL"

	// SpanKindRetriever identifies a span that retrieves documents.
	SpanKindRetriever OpenInferenceSpanKind = "RETRIEVER"

	// SpanKindReranker identifies a span that reranks documents.
	SpanKindReranker OpenInferenceSpanKind = "RERANKER"

	// SpanKindEmbedding identifies a span that creates embeddings.
	SpanKindEmbedding OpenInferenceSpanKind = "EMBEDDING"

	// SpanKindAgent identifies a span that runs an agent.
	SpanKindAgent OpenInferenceSpanKind = "AGENT"

	// SpanKindGuardrail identifies a span that applies a guardrail.
	SpanKindGuardrail OpenInferenceSpanKind = "GUARDRAIL"

	// SpanKindEvaluator identifies a span that evaluates a result.
	SpanKindEvaluator OpenInferenceSpanKind = "EVALUATOR"
)

// MimeType represents common MIME types used in OpenInference.
type MimeType string

const (
	// MimeTypeText is the plain text MIME type.
	MimeTypeText MimeType = "text/plain"

	// MimeTypeJSON is the JSON MIME type.
	MimeTypeJSON MimeType = "application/json"

	// MimeTypeAudioWAV is the WAV audio MIME type.
	MimeTypeAudioWAV MimeType = "audio/wav"
)

// LLMSystem represents the AI product as identified by the client or server.
type LLMSystem string

const (
	LLMSystemOpenAI    LLMSystem = "openai"
	LLMSystemAnthropic LLMSystem = "anthropic"
	LLMSystemMistralAI LLMSystem = "mistralai"
	LLMSystemCohere    LLMSystem = "cohere"
	LLMSystemVertexAI  LLMSystem = "vertexai"
	LLMSystemAI21      LLMSystem = "ai21"
	LLMSystemMeta      LLMSystem = "meta"
	LLMSystemAmazon    LLMSystem = "amazon"
)

// LLMProvider represents the provider of the LLM inferences.
type LLMProvider string

const (
	LLMProviderOpenAI    LLMProvider = "openai"
	LLMProviderAnthropic LLMProvider = "anthropic"
	LLMProviderMistralAI LLMProvider = "mistralai"
	LLMProviderCohere    LLMProvider = "cohere"
	LLMProviderGoogle    LLMProvider = "google"
	LLMProviderAWS       LLMProvider = "aws"
	LLMProviderAzure     LLMProvider = "azure"
	LLMProviderXAI       LLMProvider = "xai"
	LLMProviderDeepSeek  LLMProvider = "deepseek"
)
